{"cells":[{"cell_type":"markdown","source":"It looks like this file is in not in utf-8 encoding. When you try to read into Python using pd.read_csv, you'll get this error:\n\n> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 2: invalid start byte","metadata":{}},{"cell_type":"code","source":"import numpy as np # linear algebra\nimport pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)\n\ndf = pd.read_csv(\"../input/PoliceKillingsUS.csv\")\ndf.head()","outputs":[],"execution_count":null,"metadata":{"_uuid":"cccd9f1257bfd74f9b3f6c070e0330b60bc0d4e2","_cell_guid":"ecff926c-b412-4f13-aa3c-453c29c9be01"}},{"cell_type":"markdown","source":"Fortunantly, the fix is relatively simple! We just need to tell Python the actual encoding of this file. After some trail and error, I figured out that it was in windows-1252 encoding. (You can find out more [here if you're curious](https://www.w3schools.com/charsets/ref_html_ansi.asp)). This is probably becuase these files were saved on a Windows computer at some point and this was the default character encoding for that computer.\n\nTo read in the files, all we need to do is add the \"encoding\" argument to read_csv and tell it the correct encoding, like so:\n","metadata":{}},{"cell_type":"code","source":"df = pd.read_csv(\"../input/PoliceKillingsUS.csv\", encoding=\"windows-1252\")\ndf.head()","outputs":[],"execution_count":null,"metadata":{}},{"cell_type":"markdown","source":"Hope this helps! Happy analyzing. :)","metadata":{}}],"nbformat":4,"nbformat_minor":1,"metadata":{"kernelspec":{"language":"python","name":"python3","display_name":"Python 3"},"language_info":{"name":"python","file_extension":".py","version":"3.6.1","codemirror_mode":{"version":3,"name":"ipython"},"mimetype":"text/x-python","pygments_lexer":"ipython3","nbconvert_exporter":"python"}}}